version: '3'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.6.0'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - './elasticdata:/usr/share/elasticsearch/data'
    environment:
      - discovery.type=single-node
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.6.0'
    ports:
      - '5601:5601'
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'

  python:
    build: .
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
      - kibana

  node:
    image: 'node:latest'
    working_dir: /home/node/app
    command:
    - /bin/sh
    - '-c'
    - 'npm install && npm start & npm run watch-css'
    ports:
    - '3000:3000'
    volumes:
    - './app:/home/node/app'